### ISSUE TITLE
Filament 2

### ISSUE THREAD

**Issue by martin-ro** [nop-app/filament#1]
Hi,

is there any plans to release the package for Filament 2?

Cheers,

Martin

**Comment by danilopolani** [comment]
Hi Martin,
you're totally right, I'll take a look into it in the new few days and keep you updated :)

Thank you!

**Comment by martin-ro** [comment]
Thanks, appreciate it!

**Comment by danilopolani** [comment]
> Thanks, appreciate it!

v2.0.0 released with support for Filament v2! Let me know if you encounter any issues, in the meanwhile, I'm just gonna close this.

Thank you!
